//Patient login jwt token
POST http://localhost:6000/appointment/create
Authorization: Bearer jwt token
Content-Type: application/json

{
    "doctorID" : "MongoDbID",
    "patientID" : "MongoDbID",
    "time" : "Date/Time (string)"
}

###

//Doctor login jwt token
POST http://localhost:6000/treatment/add/MongoDbID(Appointment)
Authorization: Bearer jwt token
Content-Type: application/json

{
    "appointmentID" : "MongoDbID",
    "treatment" : "Prescirption"
}

###

//Doctor login jwt token
PATCH http://localhost:6000/appointment/update/MongoDbID(Appointment)
Authorization: Bearer jwt token
Content-Type: application/json

