//Doctor login jwt token 
GET http://localhost:6000/dashboard/doctor/appointments_details/MongoDbID(Doctor)
Authorization: Bearer jwt token
Content-Type: application/json

###

//Doctor login jwt token 
GET http://localhost:6000/dashboard/doctor/appointments/MongoDbID(Doctor)
Authorization: Bearer jwt token
Content-Type: application/json

###

//Patient login jwt token 
GET http://localhost:6000/dashboard/patient/activeDoctors
Authorization: Bearer jwt token
Content-Type: application/json

###

//Patinet login jwt token 
GET http://localhost:6000/dashboard/patient/appointments/MongoDbID(Patient)
Authorization: Bearer jwt token
Content-Type: application/json
